### PR TITLE
#layout: line-height for headings

### PR DESCRIPTION
**Pull request by yegor256**
Would be great to merge this and release a new version. Thanks.

### CODE REVIEW

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
@filfreire please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#132` is in scope.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/tacit#132`.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#132` is now out of scope.

**Pull request merged**
