### PR TITLE
 #31 browser compatibility table

### PR DESCRIPTION
**Pull request by filfreire**
@yegor256 please follow-up. This is related to issue #31

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#95` is in scope.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @filfreire, total is [+135](http://www.0crat.com/u/filfreire).

**Comment by yegor256** [comment]
@filfreire looks good to me, but I thought that we would put it into README.

**Comment by filfreire** [comment]
@yegor256 please check again

**Comment by yegor256** [comment]
@filfreire love it!

**Comment by filfreire** [comment]
@rultor merge

**Pull request merged**
