### PR TITLE
#109 - add git commit guidelines

### PR DESCRIPTION
**Pull request by filfreire**
Related to issue #109.

@yegor256 FYI

### CODE REVIEW

**Comment by yegor256** [comment]
@filfreire looks good, thanks

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/tacit#131`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/tacit#131` is not in scope.

**Pull request merged**
