### PR TITLE
 #74 update index footer date

### PR DESCRIPTION
**Pull request by filfreire**
Fix for https://github.com/yegor256/tacit/issues/74

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#75` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @filfreire, total is [+75](http://www.0crat.com/u/filfreire).

**Comment by filfreire** [comment]
@yegor256 please CR/merge
Also created issue https://github.com/yegor256/tacit/issues/76 to add a validation on date.

This PR closes issue https://github.com/yegor256/tacit/issues/74
and can also close PR https://github.com/yegor256/tacit/pull/47 related to 2016.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
