### PR TITLE
Built with Tacit: Add list

### PR DESCRIPTION
**Pull request by 0x13a**
I am not sure it's how you like it, we might not even need to use the Google Form, but just accept PRs for the list *Built with Tacit*

Solves #113

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#115` is in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#115` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
@0x13a The head repository is missing, could you kindly delete this PR, create the fork of the repo again and open a new one PR?

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#115` is now out of scope.

**Comment by 0crat** [comment]
Payment to ARC for closed pull request.: +15 points just awarded to @filfreire, total is [+390](http://www.0crat.com/u/filfreire).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @filfreire, total is [+390](http://www.0crat.com/u/filfreire).

**Pull request closed without merging**
