### PR TITLE
Minor grammar improvement

### PR DESCRIPTION
**Pull request by jamesrom**
This typo jumped out at me, here's a quick fix.

### CODE REVIEW

**Comment by homeworkprod** [comment]
While we're at it: I suggest to rename `_headers.scss` (whose name confuses me) to `_headings.scss`.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@homeworkprod can you please submit a new PR for your correction?

**Comment by homeworkprod** [comment]
@yegor256, of course, here you go: #41

**Comment by yegor256** [comment]
@rultor try to merge again

**Comment by yegor256** [comment]
@jamesrom thanks!

**Pull request merged**
