### PR TITLE
Issue loading images on icon and top of index.html

### PR DESCRIPTION
**Pull request by filfreire**
Related issue  #128

### CODE REVIEW

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#129` is in scope.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/tacit#129`.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#129` is now out of scope.

**Pull request merged**
