### PR TITLE
Added some styles to form controls and main element, a bit of formating clean up as well.

### PR DESCRIPTION
**Pull request by h-taylor**
I gave form controls a glow when given focus, the colour is variable located in _defs.
I gave the main element display:block, this offers support for older browsers.
I made a format error myself which I corrected then I removed a bunch of trailing spaces.

### CODE REVIEW

**Comment by s4wny** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@h-taylor this is how it looks on my Chrome:

screen shot 2015-05-13 at 9 46 38 pm

**Comment by yegor256** [comment]
@h-taylor I'm not sure it's the right way to highlight a form control... let me think

**Comment by yegor256** [comment]
@h-taylor this PR seems to be outdated. Please, feel free to submit a new one, if you still think that our CSS needs improvements. Thanks!

**Pull request closed without merging**
