### PR TITLE
Add built with Tacit section

### PR DESCRIPTION
**Pull request by 0x13a**
Solves #113

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire please, pay attention to this pull request

**Comment by 0x13a** [comment]
Hi @rultor merge

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#120` is in scope.

**Comment by filfreire** [comment]
@0x13a thanks 👍

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/tacit#120`.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#120` is now out of scope.

**Pull request merged**
