### PR TITLE
we are in 2016!

### PR DESCRIPTION
**Pull request by nicolasdanelon**

### CODE REVIEW

**Comment by yegor256** [comment]
@nicolasdanelon you're right, but how about adding a check to Gruntfile, in order to prevent this from happening in the future? moreover, it's better to say `2015-2016`

**Comment by nicolasdanelon** [comment]
we may can add http://stackoverflow.com/a/20446748/1504286 or http://gruntjs.com/api/grunt.template#grunt.template.today right?

**Comment by yegor256** [comment]
@nicolasdanelon I would rather do something similar to this: https://github.com/teamed/pdd/blob/master/Rakefile#L73-L79 The point is that build should check the dates in all files and fail if some of them are expired. That way we would have a broken build already and I would fix the date a month ago. See?

**Comment by filfreire** [comment]
@yegor256 created issue https://github.com/yegor256/tacit/issues/76 to follow-up on creating a build check

+ created issue https://github.com/yegor256/tacit/issues/74 with PR with date update to "2015-2017"

**Comment by filfreire** [comment]
@yegor256 this PR can be closed, it has been fixed in the scope of https://github.com/yegor256/tacit/pull/75 

also created issue https://github.com/yegor256/tacit/issues/76 to follow-up on creating a build check for the date

**Comment by yegor256** [comment]
@filfreire closed. @nicolasdanelon thanks for your contribution anyway!

**Pull request closed without merging**
