### PR TITLE
fixed contrast issues

### PR DESCRIPTION
**Pull request by jraller**
per issue #114 I'm submitting a pull request to fix issues reported by lighthouse including color contrast.

I tried to stick as closely to the original colors as possible, altering their brightness, but retaining their hue. Hopefully a graphic designer can improve upon the values that I came up with.

https://webaim.org/resources/contrastchecker/ was used to select values that would pass all of the tests.

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#116` is in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#116` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
@jraller thanks for the contribution 👍

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#116` is now out of scope.

**Comment by 0crat** [comment]
Payment to ARC for closed pull request.: +15 points just awarded to @filfreire, total is [+345](http://www.0crat.com/u/filfreire).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @filfreire, total is [+345](http://www.0crat.com/u/filfreire).

**Pull request merged**
