### PR TITLE
 #73 add contributing.md

### PR DESCRIPTION
**Pull request by filfreire**
@yegor256 please follow-up
Related Github issue https://github.com/yegor256/tacit/issues/73

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#90` is in scope.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @filfreire, total is [+105](http://www.0crat.com/u/filfreire).

**Comment by yegor256** [comment]
@filfreire I guess we need to remove this text from README, in order to avoid duplication. We just have to leave a link to this file in README.

**Comment by filfreire** [comment]
@yegor256 done, now we leave a link to this file in README

**Comment by filfreire** [comment]
@rultor merge

**Pull request merged**
