### PR TITLE
vertical-align for TD/TH

### PR DESCRIPTION
**Pull request by yegor256**
I believe we need this.

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#119` is in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#119` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#119` is now out of scope.

**Comment by 0crat** [comment]
Payment to ARC for closed pull request.: +15 points just awarded to @filfreire, total is [+255](http://www.0crat.com/u/filfreire).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @filfreire, total is [+255](http://www.0crat.com/u/filfreire).

**Comment by filfreire** [comment]
@rultor release, tag is 1.2.0

**Comment by filfreire** [comment]
@rultor release, tag is `1.2.0`

**Pull request merged**
