### PR TITLE
Fixed rultor css dist/ script and added rultor script comments

### PR DESCRIPTION
**Pull request by jehna**

### CODE REVIEW

**Comment by jehna** [comment]
@yegor256 please check this: https://github.com/jehna/tacit/blob/rultor-comments-and-fixes/.rultor.yml

**Comment by yegor256** [comment]
@jehna wait... we should **not** commit to master branch during release phase. We should commit to the _current_ branch and Rultor will tag it properly, see what rultor is doing: https://github.com/yegor256/rultor/blob/1.52.15/src/main/resources/com/rultor/agents/req/release.sh

**Comment by jehna** [comment]
@yegor256 wait, now I'm confused. 
Wasn't it the purpose of the #27 issue that cloning the `master` branch would have the compiled CSS files in the `dist` folder?
The idea I did here was that the rultor would push the most recent compiled CSS to `master` always on release.

So do you mean that we should commit to the current branch, where current branch being:
* the `__rultor` branch or
* the branch that is coming in as pull request (so rultor would compile & commit on merge)?

**Comment by yegor256** [comment]
@jehna we can't (shouldn't) touch the master branch on release. The release procedure is simple:

 * rultor creates a new supplementary branch (called `__rultor` usually)
 * we make all the necessary changes we want and commit them
 * rultor tags our last commit in `__rultor` as `0.5.4` (or whatever we need)
 * rultor pushes the tag to Github

So, all changes that we should make must stay in the current branch (`__rultor`). We should create `dist` directory there, commit `css` files there, etc. Make sense?

**Comment by jehna** [comment]
@yegor256 but pushing to the `__rultor` branch does not quite resolve the orifinal issue #27 :
> When using tacit with bower it would be usefull to have tacit.min.css and tacit.css in a dist folder ...  It is not possible to start working with tacit by just cloning the repository.

Or should we ditch this approach (automatic build with Rultor) and just allow the devs to commit the `/dist` folder themselves?

**Comment by yegor256** [comment]
@jehna I think we should just make sure that during the release we do create files in `dist` folder and then commit them to the current branch (`__rultor` or whatever it is). Now it's not happening, that's why we don't see them in release tags. I think the problem is that they are ignored in `.gitignore`

**Comment by jehna** [comment]
The already ongoing rultor script does already push the compiled css to the [gh-pages](https://github.com/yegor256/tacit/tree/gh-pages) branch, so I think if the users just can checkout to the correct branch, they can start using the source without building the project with `grunt`.

So the question that I think remains is that does the issue #27 really need the compiled to two different places if either of those places is not the `master` branch (that would allow even the users with no git knowledge to start using the library). If the user knows how to checkout to the tag, they should be able to also checkout to the `gh-pages` branch to get the compiled css.

The issue:
>  It is not possible to start working with tacit by just cloning the repository

**Comment by yegor256** [comment]
@jehna `gh-pages` is something completely different. we need to commit that `css` files to `__rultor` branch, in order to make them available in releases, for example here: https://github.com/yegor256/tacit/tree/0.5.4

**Comment by yegor256** [comment]
@jehna do you want to continue with this PR? Or we can close it? I really like the comments you added to the script, but not all the changes are acceptable. Maybe you can just leave the comments there for now and all other changes we'll try to do in further PRs?

**Comment by jehna** [comment]
@yegor256 ah, totally forgot about this. let me revisit the pr when I get some time and let's figure it out :)

**Comment by yegor256** [comment]
@jehna thanks!)

**Comment by jehna** [comment]
@yegor256 rebased and only left the comments. No extra commits on the `master` branch :)

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
