### PR TITLE
Update readme with gem installs for scss_lint and compass.

### PR DESCRIPTION
**Pull request by mrben**
Hi

To get Grunt running I had to install scss-lint and compass, I've added it to the README in case you think it's a worthwhile addition.

Many thanks
Ben.

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@rultor try to merge again

**Comment by yegor256** [comment]
@mrben thanks!

**Comment by mrben** [comment]
@yegor256 :+1:

**Pull request merged**
