### PR TITLE
no flex

### LINKED ISSUE #211: fiedset rendering is broken in latest Chrome
Open this page: https://yegor256.github.io/tacit/

The `fieldset` part is not rendering elements vertically.

### PR DESCRIPTION
**Pull request by yegor256**
I removed `flex` from `fieldset` to fix #211

### CODE REVIEW

**Comment by yegor256** [comment]
@filfreire let's review and merge and release please?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @filfreire[/z](https://www.0crat.com/u/filfreire) please review this and merge or reject

**Review by filfreire — APPROVED** [review]
@yegor256 looks good to me, tried it out locally with a chromium browser:

chromium


going to try merge and release now

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#214` is not assigned, can't get performer

**Pull request merged**
