### PR TITLE
buttons and def

### PR DESCRIPTION
**Pull request by mmbug**

### CODE REVIEW

**Comment by filfreire** [comment]
@yegor256 I think we can merge this one.
I checked out @maxbugaenko branch locally and with the changes tacit looks a bit nicer. But this is subjective.

What do you think?

**Comment by yegor256** [comment]
@filfreire yes, let's merge, but there are some merge conflicts

**Comment by filfreire** [comment]
@mmbug @maxbugaenko could you kindly fix the conflicts on `scss/_forms.scss`?

**Comment by filfreire** [comment]
@yegor256 please close this PR

**Comment by filfreire** [comment]
@yegor256 conflicts haven't been solved so far. We should close and I submit from my form.

**Comment by yegor256** [comment]
@filfreire closed

**Pull request closed without merging**
