### PR TITLE
#145 - Add contributing info to readme

### PR DESCRIPTION
**Pull request by filfreire**
PR to tackle issue #145 
/cc @alex-semenyuk 

@yegor256 please review.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#146](https://github.com/yegor256/tacit/issues/146) is now in scope, role is `REV`

**Comment by filfreire** [comment]
@yegor256 I'm merging this PR since it contains the how-to-build info that is currently missing and is important for new contributors. If you think something should be changed, feel free to commit a fix afterward.

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#146](https://github.com/yegor256/tacit/issues/146) is now out of scope

**Pull request merged**
