### PR TITLE
Aside

### PR DESCRIPTION
**Pull request by dz-s**
#103 
@filfreire @yegor256 please, describe what other options you would like see (like borders, margins, font-size etc.) and i will add them to corresponding `.sass` files.

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#190](https://github.com/yegor256/tacit/issues/190) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `REV` is banned at [#190](https://github.com/yegor256/tacit/issues/190); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `REV` is banned at [#190](https://github.com/yegor256/tacit/issues/190); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by dz-s** [comment]
@filfreire could we add or create some tool to sort out all properties in an alphabetical order? I'm not so smart to think about it every time to figure out what property should be added first.

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `REV` is banned at [#190](https://github.com/yegor256/tacit/issues/190); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by filfreire** [comment]
> @filfreire @yegor256 could we add or create some tool (like onsave it will be reorder props like Go formatter does) to sort out all properties in an alphabetical order? I'm not so smart to think about it every time to figure out what property should be added first.
> 
> Would it be possible to add it to the build process such task (might be grunt task or just a separate function) if i create one? Thanks.

@dz-s sounds like a good idea, create a ticket for it, we could have a lint task to sort the properties locally

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#190` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#190](https://github.com/yegor256/tacit/issues/190) is now out of scope

**Pull request merged**
