### PR TITLE
 #88 - add Tacit logo

### PR DESCRIPTION
**Pull request by filfreire**
PR #122 doesn't seem to have worked properly, created a new branch with all the work on it.

### CODE REVIEW

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#123` is in scope.

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
@yegor256 i need a hand here, i don't get why this 

```error: Your local changes to the following files would be overwritten by checkout:
	images/tacit_logo.png
Please, commit your changes or stash them before you can switch branches.
Aborting
'cid' file is absent, container wasn't started correctly```

is happening.

**Comment by yegor256** [comment]
@filfreire I think you need to mark `*.png` files as binary in https://github.com/yegor256/tacit/blob/master/.gitattributes

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
@yegor256 thanks for the `.gitattributes` tip.
merged.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/tacit#123`.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#123` is now out of scope.

**Pull request merged**
