### PR TITLE
Plain text to <label> element

### PR DESCRIPTION
**Pull request by teriyakigod2**
#78

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this pull request

**Comment by filfreire** [comment]
@teriyakigod2 can you open a new PR only with this specific change on a specific branch (instead of doing it from master branch)?

**Comment by 0crat** [comment]
@teriyakigod2[/z](https://www.0crat.com/u/teriyakigod2) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @filfreire[/z](https://www.0crat.com/u/filfreire) please review this and merge or reject

**Comment by teriyakigod2** [comment]
@filfreire sure, will do it in a couple of hours.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#181` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request closed without merging**
