### PR TITLE
#inline-block: nav alignment

### PR DESCRIPTION
**Pull request by yegor256**
The responsive layout is broken, if we don't have these.

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#142](https://github.com/yegor256/tacit/issues/142) is now in scope, role is `REV`

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#142` is not assigned, can't get start time

**Comment by filfreire** [comment]
@rultor release, tag is `1.2.8`

**Comment by filfreire** [comment]
@yegor256 merged and released.

**Comment by 0crat** [comment]
The job [#142](https://github.com/yegor256/tacit/issues/142) is now out of scope

**Comment by 0crat** [comment]
Job [#142](https://github.com/yegor256/tacit/issues/142) was not in scope

**Comment by yegor256** [comment]
@filfreire thanks!

**Pull request merged**
