### PR TITLE
Remove default outline: 0

### PR DESCRIPTION
**Pull request by SaraVieira**
Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:

  - You made a small amount of changes (less than 100 lines, less than 10 files)
  - You made changes related to only one bug (create separate PRs for separate problems)
  - You are ready to defend your changes (there will be a code review)
  - You don't touch what you don't understand
  - You ran the build locally and it passed

This article will help you understand what we are looking for: http://www.yegor256.com/2015/02/09/serious-code-reviewer.html

Thank you for your contribution!

----

Hello,

Having an outline of 0 makes the links and buttons unusable by keyboard and creates huge problems with accessibility

http://www.outlinenone.com/

### CODE REVIEW

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
@rultor release, tag is `1.3.6`

**Comment by filfreire** [comment]
@SaraVieira thank you 👍 
Merged and released on https://github.com/yegor256/tacit/releases/tag/1.3.6

/cc @yegor256

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#173` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by SaraVieira** [comment]
Thank you :D

**Pull request merged**
