### PR TITLE
change the link #97

### PR DESCRIPTION
**Pull request by akshayvinchurkar1**
change the link #97

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#98` is in scope.

**Comment by filfreire** [comment]
@akshayvinchurkar1 could you change to ``` https://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-VERSION.min.css```?

**Comment by filfreire** [comment]
@akshayvinchurkar1 
> could you change to `https://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-VERSION.min.css` ?

**Comment by filfreire** [comment]
@akshayvinchurkar1 could you kindly change the link to `https://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-VERSION.min.css`?
So I can then merge this PR.

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
This PR closes #60 and #97

**Comment by sobolevn** [comment]
Nice!

**Pull request merged**
