### PR TITLE
display table

### PR DESCRIPTION
**Pull request by yegor256**
I believe, this is how it should be.

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this pull request

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @filfreire[/z](https://www.0crat.com/u/filfreire) please review this and merge or reject

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#154` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by filfreire** [comment]
@rultor release, tag is `1.3.0`

**Comment by filfreire** [comment]
@yegor256 this change is now under `1.3.0`, thanks!

**Comment by yegor256** [comment]
@filfreire cool, thanks!

**Pull request merged**
