### PR TITLE
These sites are no longer available (jare.io, wring.io)

### PR DESCRIPTION
**Pull request by RALMAZ**
Sites:
- [jare.io](https://jare.io)
- [wring.io](https://wring.io)

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this pull request

**Comment by 0crat** [comment]
@RALMAZ this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @filfreire[/z](https://www.0crat.com/u/filfreire) please review this and merge or reject

**Comment by RALMAZ** [comment]
Resolved by Yegor256

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#209` is not assigned, can't get performer

**Pull request closed without merging**
