### PR TITLE
Bump date 2019

### PR DESCRIPTION
**Pull request by filfreire**
`npm test` command currently fails with date validation. Updating date across all needed files.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#175](https://github.com/yegor256/tacit/issues/175) is now in scope, role is `REV`

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `REV` is banned at [#175](https://github.com/yegor256/tacit/issues/175); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
@yegor256 can you "hard" merge this one?

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#175](https://github.com/yegor256/tacit/issues/175) is now out of scope

**Pull request merged**
