### PR TITLE
no radius for the border

### PR DESCRIPTION
**Pull request by yegor256**
Let's get rid of the radius for the `<article>`

### CODE REVIEW

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
@rultor release, tag is `1.5.1`

**Comment by filfreire** [comment]
@yegor256 released in version `1.5.1`. thanks :+1:

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this pull request

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this pull request is too small, just 5 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @filfreire[/z](https://www.0crat.com/u/filfreire) please review this and merge or reject

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@9a947b19-47b2-43b3-a098-15eb9dcbb263, thread: pool-5-thread-6
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "orders.xml" in "C7BNDNSNR" in 2min: java.util.concurrent.locks.ReentrantLock@2b9d2c54[Locked by thread pool-5-thread-1]
```

[0.48.2](https://github.com/zerocracy/farm): CID: [22220f4c-515d-44fe-9418-675266b62ce6](https://www.0crat.com/footprint/C7BNDNSNR/22220f4c-515d-44fe-9418-675266b62ce6), Type: "Close job"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@9a947b19-47b2-43b3-a098-15eb9dcbb263, thread: pool-5-thread-6
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "wbs.xml" in "C7BNDNSNR" in 2min: java.util.concurrent.locks.ReentrantLock@2b9d2c54[Locked by thread pool-5-thread-1]
```

[0.48.2](https://github.com/zerocracy/farm): CID: [22220f4c-515d-44fe-9418-675266b62ce6](https://www.0crat.com/footprint/C7BNDNSNR/22220f4c-515d-44fe-9418-675266b62ce6), Type: "Close job"

**Pull request merged**
