### PR TITLE
Add dist/ folder with .css, .min.css and .min.css.map files to GitHub

### LINKED ISSUE #27: Add compiled file to a dist folder
When using tacit with bower it would be usefull to have `tacit.min.css` and `tacit.css` in a dist folder

### PR DESCRIPTION
**Pull request by jehna**
@yegor256 can you check the rultor script modifications? This change should push the newest compiled css files in the `dist/` folder automatically to the master branch. 

Fixes #27

### CODE REVIEW

**Comment by yegor256** [comment]
@jehna you think this is not a problem? https://github.com/yegor256/tacit/blob/master/.gitignore#L7

**Comment by jehna** [comment]
@yegor256 that's why the rultor should `add -f` it ;)

The idea is that the developer should not be able to add the file. The rultor should do the compilation and adding automatically to avoid manual errors (and merge conflicts).

**Comment by jehna** [comment]
@yegor256 or should rultor do the adding on merge?

**Comment by yegor256** [comment]
@jehna aha, got it, let's try

**Comment by yegor256** [comment]
@rultor merge

**Comment by jehna** [comment]
@yegor256 ok, can we try the release?

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.4`

**Comment by jehna** [comment]
Ok, no `dist/` at the first build :(

**Comment by jehna** [comment]
@yegor256 a new pull request to fix this error?

**Comment by yegor256** [comment]
@jehna yes, please

**Pull request merged**
