### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by vassilevsky**

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this pull request

**Comment by 0crat** [comment]
@vassilevsky[/z](https://www.0crat.com/u/vassilevsky) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @filfreire[/z](https://www.0crat.com/u/filfreire) please review this and merge or reject

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
@vassilevsky released in version `1.5.1`. thanks :+1:

**Pull request merged**
