### PR TITLE
more projects to the list

### PR DESCRIPTION
**Pull request by yegor256**
More project to the list

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire please, pay attention to this pull request

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#121` is in scope.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/tacit#121`.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#121` is now out of scope.

**Pull request merged**
