### PR TITLE
validate grunt task

### PR DESCRIPTION
**Pull request by dz-s**
#91

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#186](https://github.com/yegor256/tacit/issues/186) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#186` already assigned to @filfreire, can't assign to @filfreire

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#186` already assigned to @filfreire, can't assign to @filfreire

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#186` already assigned to @filfreire, can't assign to @filfreire

**Comment by 0crat** [comment]
The job [#186](https://github.com/yegor256/tacit/issues/186) assigned to @filfreire[/z](https://www.0crat.com/u/filfreire), here is [why](https://www.0crat.com/footprint/C7BNDNSNR/88c61c63-69e9-4d8b-915d-89b7b7649523); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
@dz-s merged, thanks 👍

**Comment by 0crat** [comment]
The job [#186](https://github.com/yegor256/tacit/issues/186) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @filfreire[/z](https://www.0crat.com/u/filfreire)

**Pull request merged**
