### PR TITLE
Add other tacit related frameworks #163

### PR DESCRIPTION
**Pull request by filfreire**
Related issue #163

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#164](https://github.com/yegor256/tacit/issues/164) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `REV` is banned at [#164](https://github.com/yegor256/tacit/issues/164); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#164` is not assigned, can't get performer

**Pull request merged**
