### PR TITLE
Add use case: tinyfts

### PR DESCRIPTION
**Pull request by dbohdan**
**[tinyfts](https://github.com/dbohdan/tinyfts)** is a very small open source full text search server that uses Tacit for its Web UI.  ~[Demo](https://tws.dbohdan.com/).~

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this pull request

**Comment by 0crat** [comment]
@dbohdan[/z](https://www.0crat.com/u/dbohdan) this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @filfreire[/z](https://www.0crat.com/u/filfreire) please review this and merge or reject

**Comment by dbohdan** [comment]
The demo has since gone down.  Here is a screenshot of what it looked like.

tinyfts-screenshot

**Comment by filfreire** [comment]
@rultor merge

**Review by filfreire — APPROVED** [review]

**Pull request merged**
