### PR TITLE
Added logical heading styles for H4, H5 and H6

### PR DESCRIPTION
**Pull request by s4wny**
H4, H5 and H6 should attract less attention than H1, H2 and H3 ;)

### Currently
Before

### After pull request
Now

### CODE REVIEW

**Comment by s4wny** [comment]
Also made <strong> bold.

### Currently

Now

### After

After

**Comment by s4wny** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@s4wny thanks for your contribution!

**Comment by yegor256** [comment]
@rultor release, tag is `0.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.4`

**Comment by yegor256** [comment]
@s4wny your changes are released in version 0.4

**Pull request merged**
