### PR TITLE
 #162 Add demo nav menu to index.html

### PR DESCRIPTION
**Pull request by filfreire**

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) this pull request is too small, just 8 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @filfreire[/z](https://www.0crat.com/u/filfreire) please review this and merge or reject

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
@rultor release, version is `1.3.3`

**Comment by filfreire** [comment]
@rultor release, tag is `1.3.3`

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#168` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
