### PR TITLE
Margin

### PR DESCRIPTION
**Pull request by yegor256**

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#139` is now in scope.

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/tacit#139` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#139` is now out of scope.

**Comment by filfreire** [comment]
@rultor release, tag is `1.2.7`

**Comment by yegor256** [comment]
@filfreire thanks!

**Pull request merged**
