### PR TITLE
Pretty fonts :)

### PR DESCRIPTION
**Pull request by edwr**
Yay! Use pretty system fonts in modern browsers :grin:

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this pull request

**Comment by filfreire** [comment]
Hi @edwr thank you for submitting a PR! 🙂 

Any chance you can provide screenshots of the end-result?

**Comment by 0crat** [comment]
@edwr[/z](https://www.0crat.com/u/edwr) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @filfreire[/z](https://www.0crat.com/u/filfreire) please review this and merge or reject

**Comment by edwr** [comment]
Windows screenshot

Ubuntu screenshot


`system-ui` uses the system font of the os (`segoe-ui` on windows and `ubuntu` on ubuntu).

Unfortunately I can't show you a screenshot from MacOS (I don't own a mac 😭).

**Comment by filfreire** [comment]
@edwr looks good to me. Later today I'll see if I can test it on a Mac and if all is well I think we're clear to merge.

@yegor256 any issues on your side with this change?

**Comment by filfreire** [comment]
@edwr sorry, forgot about following-up to this PR. Will do so ASAP.

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#169` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by filfreire** [comment]
@rultor release, tag is `1.3.8`

**Pull request merged**
