### PR TITLE
add a w3c css batch next to github stars batch

### PR DESCRIPTION
**Pull request by akshayvinchurkar1**
issue or recommendation #91 
since I check it myself it's clean and perfect so I add that batch in the index.html

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#96` is in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#96` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by filfreire** [comment]
@akshayvinchurkar1 thank you, seems ok, will try to merge now

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
@filfreire resigned from `gh:yegor256/tacit#96`, please stop working.

**Pull request merged**
