### PR TITLE
README.md: remove broken link to versioneye

### PR DESCRIPTION
**Pull request by php-coder**
versioneye service is no longer exist.

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this pull request

**Comment by 0crat** [comment]
@php-coder[/z](https://www.0crat.com/u/php-coder) this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @filfreire[/z](https://www.0crat.com/u/filfreire) please review this and merge or reject

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
@php-coder merged. Thank you 👍

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#166` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
