### PR TITLE
#143 A small mistake with href in README

### PR DESCRIPTION
**Pull request by alex-semenyuk**
#143

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#144](https://github.com/yegor256/tacit/issues/144) is now in scope, role is `REV`

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#144](https://github.com/yegor256/tacit/issues/144) is now out of scope

**Comment by filfreire** [comment]
@alex-semenyuk thank you 👍

**Pull request merged**
