### PR TITLE
Bump year version to 2018

### PR DESCRIPTION
**Pull request by filfreire**
Bump year to 2018

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#138` is now in scope.

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/tacit#138` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#138` is now out of scope.

**Comment by filfreire** [comment]
@rultor release, tag is `1.2.6`

**Pull request merged**
