### PR TITLE
layout rollback

### PR DESCRIPTION
**Pull request by yegor256**
Let's roll back some recent changes, they were wrong

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `REV` is banned at [#161](https://github.com/yegor256/tacit/issues/161); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by filfreire** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#161` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#161](https://github.com/yegor256/tacit/issues/161) is now out of scope

**Comment by filfreire** [comment]
@rultor release, tag is `1.3.2`

**Comment by filfreire** [comment]
@yegor256 done, available under `1.3.2`

**Pull request merged**
