### PR TITLE
less version

### PR DESCRIPTION
**Pull request by urn2**
add a less version

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#155](https://github.com/yegor256/tacit/issues/155) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@urn2 @filfreire wow, this is a lot of work, but what is the point of this?? If we have two versions, how we will sync changes?

**Comment by filfreire** [comment]
@urn2 I'm closing this PR. Feel free to re-open a new one following-up to the code review comments.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#155` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#155](https://github.com/yegor256/tacit/issues/155) is now out of scope

**Pull request closed without merging**
