### PR TITLE
#128 - fix images path on index.html

### PR DESCRIPTION
**Pull request by filfreire**

### CODE REVIEW

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
@rultor release, tag is `1.2.3`

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#130` is in scope.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/tacit#130`.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#130` is now out of scope.

**Pull request merged**
