### PR TITLE
Create a Logo for Tacit #88

### PR DESCRIPTION
**Pull request by filfreire**
@yegor256  FYI

Finally got around to create the PR with the logo svg file and a png version also on the readme.

This closes issue #88

@akshayvinchurkar / @akshayvinchurkar1 thank you for the logo. I mentioned you as the designer on the README.

### CODE REVIEW

**Comment by filfreire** [comment]
@yegor256 this is how it looks on the REAME:
screen shot 2017-12-05 at 00 03 18

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#122` is in scope.

**Comment by yegor256** [comment]
@filfreire looks good to me!

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
closing this PR and re-attempting to merge with PR https://github.com/yegor256/tacit/pull/123

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/tacit#122`.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#122` is now out of scope.

**Pull request closed without merging**
