### PR TITLE
 #86 add license to README

### PR DESCRIPTION
**Pull request by filfreire**
Issue https://github.com/yegor256/tacit/issues/86

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#87` is in scope.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @filfreire, total is [+90](http://www.0crat.com/u/filfreire).

**Comment by filfreire** [comment]
@yegor256 please CR and follow-up

Also have a question, why did I get the message 

> Bug was reported: +15 points just awarded to @filfreire, total is +90.

Why "Bug was reported", does the message make sense? Could it be a bug and the message is wrong?

**Comment by yegor256** [comment]
@filfreire it's a bug, we're working on it: https://github.com/zerocracy/datum/issues/94

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
