### PR TITLE
sub and sub elements style added

### PR DESCRIPTION
**Pull request by akshayvinchurkar1**
sub and sub elements style added in typography scss file

### CODE REVIEW

**Comment by 0crat** [comment]
@filfreire please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#118` is in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#118` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by filfreire** [comment]
@rultor merge

**Comment by filfreire** [comment]
@akshayvinchurkar1 thanks for your contribution. I'll reply to your question on issue https://github.com/yegor256/tacit/issues/110 asap.

**Comment by 0crat** [comment]
Job `gh:yegor256/tacit#118` is now out of scope.

**Comment by 0crat** [comment]
Payment to ARC for closed pull request.: +15 points just awarded to @filfreire, total is [+300](http://www.0crat.com/u/filfreire).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @filfreire, total is [+300](http://www.0crat.com/u/filfreire).

**Pull request merged**
