### PR TITLE
Added: Table responsiveness

### PR DESCRIPTION
**Pull request by jehna**
Tested to work on ios, android (chrome + native), latest chrome + FF + safari, IE10+.

IE9 buggy, the table does not understand css well.

### CODE REVIEW

**Comment by yegor256** [comment]
@jehna why do we have this in `_responsive` instead of `_tables`?

**Comment by jehna** [comment]
I thought it was wiser to contain only to small screen sizes, but it can also be the default behaviour so large tables won't overflow the main content?

**Comment by yegor256** [comment]
@jehna yes, I think that would be logical

**Comment by jehna** [comment]
@yegor256 changed to `_tables`

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.5`

**Comment by yegor256** [comment]
@jehna thanks!

**Pull request merged**
